### ISSUE TITLE
To-Do's for Stanley

### ISSUE THREAD

**Issue by george536** [nguyes44/MacTransit#17]
**To-Do:**
- [x] Please change repo name
- [x] Please make PR to update team name
- [x] Please make PR to update project name
