### ISSUE TITLE
To-Do's for Survey

### ISSUE THREAD

**Issue by nguyes44** [nguyes44/MacTransit#25]
**To-Do:**
- [ ] Create questions
- [ ] Make the survey
- [ ] Print out posters for it
- [ ] Get Dean's clearance to put them around

**STALLED/BLOCKED:**
- [ ] [Reason: ]

**Comment by nguyes44** [comment]
Potential Survey Questions from #27 

1. How often do you take the shuttle bus?
2. On average, how large is your wait time for a shuttle bus?
3. How often do you miss the shuttle bus you expected to take? By how much time?
4. How frustrated are you when you miss your shuttle bus, or wait a long time to hop on the next one?
5. On average, how much do you have to wait for the NEXT shuttle bus if you missed the current one?
6. If you were able to see where shuttle buses were on campus, would you consider waiting for them? And for how long?
7. What information would you want to see related to shuttle bus transportation on and off campus?
8. In an app that could provide live tracking for shuttle buses on/off campus, what information would you find the most important to see?
9. If you were to create your own transit app for shuttle buses on/off campus, what are some things that you might include that would improve your commuting experience?
10. How difficult was/is it to learn where the shuttle bus stops are on a given route?
11. Would you plan your commute to campus around shuttle bus arrival times, if possible?
12. If applicable, tell us (in detail) about a negative shuttle bus experience.
13. If you would like to be involved in an interview / testing session, please provide us an email with which we can contact you at a later date.
14. Would seeing the capacity of a bus make you feel more/less inclined to waiting for it?

Action Items

- [ ] Sort questions in an approachable manner (and potentially add MCQ answers)
- [ ] Ask around for a lamination process (to avoid bad weather outside)
- [ ] Generate a QR code compatible survey based on these results
- [ ] Post this survey to the McMaster subreddit
- [ ] Print and post this QR code with a tagline (around 10) at shuttle bus stops (upon Dean's approval)

**Comment by arvindshastri** [comment]
The survey is live and located here: https://forms.gle/DpC8AgVyNiWLULNx7
