### ISSUE TITLE
To-Do's for Revising Problem Statement / Dev Plan Deliverables

### ISSUE THREAD

**Issue by nguyes44** [nguyes44/MacTransit#26]
**To-Do:**
- [ ] accommodate for PO wanting to track also 10 Bay and Ron Joyce shuttle busses 
- [ ] remove Parking Office collaboration as a concern in POC. Driver concerns might still be present.
- [ ] add to stretch goals "giving times of other transit options, such as GO, FlixBus, HSR"
- [ ] modify data analysis stretch goal to not provide a tool for data analysis (since PO already does data analysis), but rather potentially show users conclusions from this historical data (suggested by Dr. Maccio)
- [ ] add to goals "a way to assist drivers in tracking the number of boarded passengers at a stop"

**STALLED/BLOCKED:**
- [ ] [Reason: ]
